import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Providers from "./providers"
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className="dark" style={{ colorScheme: "dark" }} suppressContentEditableWarning>
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="py-[60px] w-full min-h-screen bg-lightPrimary dark:bg-primary">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
